### ISSUE TITLE
Cloudflare turnstile doesn't work

### ISSUE THREAD

**Issue by rekayno** [adamlui/userscripts#32]
![image](https://user-images.githubusercontent.com/92271828/233358049-3696ed42-12da-412c-b5c3-d11667753672.png)

**Comment by adamlui** [comment]
@XiaoYingYo

**Comment by XiaoYingYo** [comment]
Hello, thank you for your feedback, I didn't expect this script to be used by others, thank you for your use

In addition, from the picture you provided, it seems that there are some errors that are not considered by `ChatGPT Heartbeat`. The situation in the picture you provided cannot be reproduced in my device or network status. Maybe we will consider it Solve it, but the premise, we will have this problem, in order to solve it better

@rekayno

**Comment by adamlui** [comment]
@rekayno the script was deprecated & replaced by [ChatGPT Auto Refresh ↻](https://github.com/adamlui/userscripts/tree/master/chatgpt/chatgpt-auto-refresh)
